apiVersion: v1
kind: ConfigMap
metadata:
  name: index-v2-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is an APP version2 (Canary deployment)</h1>
    </html