apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share # The name of your persistent volume.
  namespace: default
  labels:
    storage: nfs # The labels used when matching with a Persistent Volume Claim.
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.88.61 # The FQDN server name or IP of the NFS server goes here.
    path: /nfstest # The path to your NFS server volume.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share # The name of this Persistent Volume Claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # The size of the storage claim.
  storageClassName: ""
  selector:
    matchLabels:
      storage: "nfs" # The volume must have this label with this value.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-nfs
spec:
  selector:
    matchLabels:
      app: test-web-app
  template:
    metadata:
      labels:
        app: test-web-app
    spec:
      containers:
        - name: test-web-app
          image: nginx
          volumeMounts:
            - name: nfs-data
              mountPath: /data
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date) >> /data/sample; sleep 10; done"]
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-share